/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.v7.recyclerview;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int coordinatorLayoutStyle = 0x7f0300a5;
        public static final int fastScrollEnabled = 0x7f0300d1;
        public static final int fastScrollHorizontalThumbDrawable = 0x7f0300d2;
        public static final int fastScrollHorizontalTrackDrawable = 0x7f0300d3;
        public static final int fastScrollVerticalThumbDrawable = 0x7f0300d4;
        public static final int fastScrollVerticalTrackDrawable = 0x7f0300d5;
        public static final int font = 0x7f0300d8;
        public static final int fontProviderAuthority = 0x7f0300da;
        public static final int fontProviderCerts = 0x7f0300db;
        public static final int fontProviderFetchStrategy = 0x7f0300dc;
        public static final int fontProviderFetchTimeout = 0x7f0300dd;
        public static final int fontProviderPackage = 0x7f0300de;
        public static final int fontProviderQuery = 0x7f0300df;
        public static final int fontStyle = 0x7f0300e0;
        public static final int fontVariationSettings = 0x7f0300e1;
        public static final int fontWeight = 0x7f0300e2;
        public static final int keylines = 0x7f030110;
        public static final int layoutManager = 0x7f030114;
        public static final int layout_anchor = 0x7f030115;
        public static final int layout_anchorGravity = 0x7f030116;
        public static final int layout_behavior = 0x7f030117;
        public static final int layout_dodgeInsetEdges = 0x7f03011a;
        public static final int layout_insetEdge = 0x7f03011b;
        public static final int layout_keyline = 0x7f03011c;
        public static final int reverseLayout = 0x7f030156;
        public static final int spanCount = 0x7f03016d;
        public static final int stackFromEnd = 0x7f030173;
        public static final int statusBarBackground = 0x7f030179;
        